[project]
name = "advent-of-code"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "cython>=3.0.11",
    "numpy>=2.1.3",
    "pandas>=2.2.3",
    "regex>=2024.11.6",
]
